repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        additional_dependencies: ['tomli']
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.264'
  hooks:
    - id: ruff
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
        - id: poetry-check
        - id: poetry-lock
        - id: poetry-export
          args: ["-f", "requirements.txt", "-o", "requirements.txt", "--with", "dev doc"]
