repos:

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.2.0"
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0 
    hooks:
    - id: pydocstyle
      additional_dependencies: ['tomli']
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.264'
    hooks:
        - id: ruff
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.0  
    hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements-doc.txt", "--with", "doc"]
