name: Publish
on:
  release:
    types: [published]
permissions:
    contents: write
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install 
      - name: Check
        run: poetry check
      - name: Set token
        env: # Or as an environment variable
          credentials: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_TOKEN
      - name: build and publish to pypi
        run: poetry publish --build 
      - name: build and deploy documentation
        env:
          credentials: ${{secrets.DEPLO_HOOK}}
        run: curl -X POST "https://api.render.com/deploy/srv-che4rge7avja5maqeo00?key=6PaxlSeZFjc"

