name: "Publish Documentation"
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: build and deploy documentation
        env:
          credentials: ${{secrets.DEPLO_HOOK}}
        run: curl -X POST "https://api.render.com/deploy/srv-che4rge7avja5maqeo00?key=6PaxlSeZFjc"

