
---
name: Release

on:
  workflow_run:
    workflows: [check]
    types:
    - completed
    branches:
    - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --only semver
      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -o pipefail
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # run semantic-release
          poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"

